### ISSUE TITLE
How to restore user login after clearing app data?

### ISSUE THREAD

**Issue by kashyapRamChandra** [freshdesk/freshchat-android#57]
Provide any tutorials or example to restore the existing user on clearing app data. Currently document  is not matching with latest released code.

**Comment by rameshfreshworks** [comment]
Hi @kashyapRamChandra ,
You can use the restore use case for user login scenarios. 
Whenever a user logs in into the app, check if the user already has a restore id (which is a unique id be generated by Freshchat for an identified user) and restore the user so that you can restore his entire chat history.
Coming to the user clear, this can be done on the logout case. You can refer our documentation for more details.
 If your app does not deal with multiple users, you can skip this restore functionality.

**Comment by MuthuFD** [comment]
@kashyapRamChandra Hope @rameshfreshworks suggestions was helpful.
You can refer below for more details
https://support.freshchat.com/support/solutions/articles/50000000207
