### ISSUE TITLE
Allow to customize the title according to device's language and channel.

### ISSUE THREAD

**Issue by sandrocsimas** [freshdesk/freshchat-android#60]
It there a way to change the title according to the device's language for each channel?
```
List<String> tags = new ArrayList<>();
tags.add(CONVERSATION_CHANNEL_TAG);
ConversationOptions conversationOptions = new ConversationOptions().filterByTags(tags, getString(R.string.freshchat_channel_general));
Freshchat.showConversations(getApplicationContext(), conversationOptions);
```
I thought that it could be possible by filtering by a tag and setting the filteredViewTitle, but nothing happen and the title configured on the Channels Settings is displayed.

**Comment by rameshfreshworks** [comment]
Hi @sandrocsimas 
Freshchat supports configuring a channel in multiple languages. When configured, Freshchat SDK fetches the channels as per the device locale. This feature is available from the estate plan.

Coming to the tags and filter view title, Following are possible results for the tag filter 

1. Multiple channels found - Takes you to channel listing screen and filteredViewTitle will be the title of the screen instead of default title "Conversations"
2. Single-channel found - Takes you to chat screen with channel name set as the title  
3. No channel found - Takes you to a default channel with default channel name set as the title  

If you want a filtered channel name to be in a specific locale, you can set that channel name in that locale when adding channels in the agent portal.

**Comment by sandrocsimas** [comment]
In my case it's a single channel found, so to be able to localize the title I need to upgrade.
