### ISSUE TITLE
NameNotFoundException

### ISSUE THREAD

**Issue by DarshanPatel23** [freshdesk/freshchat-android#7]
[crashreport.txt](https://github.com/freshdesk/freshchat-android/files/1590969/crashreport.txt)
Plz help me with this issue...

**Comment by tryprasannan** [comment]
@DarshanPatel23 Sorry we missed this earlier. This looks like an issue because of Android (Ref : [Issue in AOSP BugTracker](https://issuetracker.google.com/issues/37048374)) updating the webview in the background (without any kind of callback/notification to the app) and causing a crash if the app is open and displaying a webview at that point in time and unfortunately there doesn't seem to be a way to workaround this.
